- name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
  wait_for:
    port: 22
    host: "{{ item }}"
    search_regex: OpenSSH
    delay: 10
  loop: "{{ EC2_Output | json_query('results[*].tagged_instances[0].dns_name') }}"