- name: Adding host
  add_host:
    name: "{{ item }}"
    groups: webinstances
    web_admin: murali@dump.com
    ansible_become: yes
    ansible_connection: ssh
  loop: "{{ EC2_Output | json_query('results[*].tagged_instances[0].dns_name') }}"
