- name: Adding host
  add_host:
    name: "{{ item }}"
    groups: webinstances
    web_admin: murali@dump.com
    ansible_user: ec2-user
    ansible_ssh_private_key_file: /home/ec2-user/environment/mykey.pem
    ansible_become: yes
    ansible_connection: ssh
  loop: "{{ EC2_Output | json_query('results[*].tagged_instances[0].dns_name') }}"